name: .NET Build

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build Dependencies
      run: dotnet build ./Speckoz.UniLinks/UniLinks.Dependencies/UniLinks.Dependencies.csproj

    - name: Build Site
      run: dotnet build ./Speckoz.UniLinks/UniLinks.Client.Site/UniLinks.Client.Site.csproj

    - name: Build API
      run: dotnet build ./Speckoz.UniLinks/UniLinks.API/UniLinks.API.csproj
